#Indigo properties file
#Tue Mar 17 19:51:24 CDT 2026
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
ambient-occlusion-mode=hybrid
always-tesselate-blocks=auto
fix-smooth-lighting-offset=auto
fix-luminous-block-ambient-occlusion=auto
